### ISSUE TITLE
NameError: global name 'Path' is not defined

### ISSUE THREAD

**Issue by kenvunz** [sagold/FuzzyFilePath#15]
I install the plugin from git and it's loaded on Sublime Text 3 Build 3095

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 158, in on_api_ready
    m.plugin_loaded()
  File "/Users/ken/Library/Application Support/Sublime Text 3/Packages/FuzzyFilePath/FuzzyFilePath.py", line 38, in plugin_loaded
    update_settings()
  File "/Users/ken/Library/Application Support/Sublime Text 3/Packages/FuzzyFilePath/FuzzyFilePath.py", line 50, in update_settings
    global_settings = Settings.update()
  File "/Users/ken/Library/Application Support/Sublime Text 3/Packages/FuzzyFilePath/common/settings.py", line 44, in update
    global_settings["PROJECT_DIRECTORY"] = Path.sanitize_base_directory(global_settings["PROJECT_DIRECTORY"])
NameError: global name 'Path' is not defined
```

**Comment by sagold** [comment]
Hi Kenvunz.
This was thrown if a project or base directory was defined in settings. The missing module is added and and published.

Thanks for the report.
