### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'replace'

### ISSUE THREAD

**Issue by Z-Clive** [sagold/FuzzyFilePath#18]
I'm using Windows 10 64bit with Sublime 3.

When `drag and drop` a folder or a file into Sublime, the console prints:

    Traceback (most recent call last):
      File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 304, in on_activated
        callback.on_activated(v)
      File "ProjectListener in C:\Users\Clive\AppData\Roaming\Sublime Text 3\Installed Packages\FuzzyFilePath.sublime-package", line 25, in on_activated
      File "ProjectListener in C:\Users\Clive\AppData\Roaming\Sublime Text 3\Installed Packages\FuzzyFilePath.sublime-package", line 38, in on_project_activated
      File "project.ProjectManager in C:\Users\Clive\AppData\Roaming\Sublime Text 3\Installed Packages\FuzzyFilePath.sublime-package", line 40, in activate_project
      File "project.ProjectManager in C:\Users\Clive\AppData\Roaming\Sublime Text 3\Installed Packages\FuzzyFilePath.sublime-package", line 65, in get_project
      File "project.Project in C:\Users\Clive\AppData\Roaming\Sublime Text 3\Installed Packages\FuzzyFilePath.sublime-package", line 28, in __init__
      File "project.Project in C:\Users\Clive\AppData\Roaming\Sublime Text 3\Installed Packages\FuzzyFilePath.sublime-package", line 36, in update_settings
      File "project.Project in C:\Users\Clive\AppData\Roaming\Sublime Text 3\Installed Packages\FuzzyFilePath.sublime-package", line 44, in evaluate_settings
      File "common.path in C:\Users\Clive\AppData\Roaming\Sublime Text 3\Installed Packages\FuzzyFilePath.sublime-package", line 14, in posix
    AttributeError: 'bool' object has no attribute 'replace'

**Comment by zmLGBBM** [comment]
@sagold This also happens when there's no valid `folders` node in `project settings`.

**Comment by sagold** [comment]
A quick check shows no errors on my side. Seems like i have to modify my virtualization tools. Based on the error i may fix this blindly.

**Comment by zmLGBBM** [comment]
@sagold Well, it's fairly easy to reproduce, just by following:

>1. Open a fresh clean `Sublime`
>2. Choose `Project->add folder to project`
>3. Remove the folder by right click in the sidebar side
>4. Now click in anywhere in the blank view
>5. Boom, open your console and you can see this error has been raised

And by now, the `window.project_data()` gives this:
```
{'settings': {'FuzzyFilePath': {}}}
```

**Comment by zmLGBBM** [comment]
@sagold I think the best way is to always check if the `folders` node is provided in settings and the path in it is actually exist.

**Comment by sagold** [comment]
@zmLGBBM Thank you very much. I can reproduce the error and will hopefully find some quiet time soon.

**Comment by sagold** [comment]
With release v0.3.0 this bug is fixed
