### ISSUE TITLE
TypeError: object of type 'bool' has no len()

### ISSUE THREAD

**Issue by Hamsterkacke** [sagold/FuzzyFilePath#23]
Hey Guys,

i am trying to use FFP with ST3 on my Windows 10 machine.

I tried everything and i'm out of ideas, why it doesn't work. 

Actviated debugging and logging and the console outputs:

`Traceback (most recent call last):
  File "C:\Program Files (x86)\Sublime Text 3\sublime_plugin.py", line 359, in on_query_completions
    res = callback.on_query_completions(v, prefix, locations)
  File "QueryCompletionListener in C:\Users\Philipp\AppData\Roaming\Sublime Text 3\Installed Packages\FuzzyFilePath.sublime-package", line 32, in on_query_completions
  File "FuzzyFilePath in C:\Users\Philipp\AppData\Roaming\Sublime Text 3\Installed Packages\FuzzyFilePath.sublime-package", line 319, in on_query_completions
  File "FuzzyFilePath in C:\Users\Philipp\AppData\Roaming\Sublime Text 3\Installed Packages\FuzzyFilePath.sublime-package", line 213, in build
  File "FuzzyFilePath in C:\Users\Philipp\AppData\Roaming\Sublime Text 3\Installed Packages\FuzzyFilePath.sublime-package", line 240, in build_needle_query
TypeError: object of type 'bool' has no len()`

This happens as soon, as i try to use src in a script tag. But it also wont work with image tages or any other tags. Also added the scope for everything from the Docs. Any hints?

**Comment by sagold** [comment]
Hi Hamsterbacke.

I fixed the conditional and published the patch 6cc7f7900a93a813c7c0d287004c72771b71f161. I hope it works after update the package.

Thanks for your Feedback
