### ISSUE TITLE
IndexError when pressed `alt+shift+right_mouse_click`

### ISSUE THREAD

**Issue by evandrocoan** [sagold/FuzzyFilePath#33]
### IndexError when pressed `alt+shift+right_mouse_click`

What is this happening when I press  `alt+shift+right_mouse_click`?
```
Traceback (most recent call last):
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\sublime_plugin.py", line 421, in on_post_text_command
    callback.on_post_text_command(v, name, args)
  File "QueryCompletionListener in D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Installed Packages\FuzzyFilePath.sublime-package", line 78, in on_post_text_command
  File "common.selection in D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Installed Packages\FuzzyFilePath.sublime-package", line 7, in get_line
  File "common.selection in D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Installed Packages\FuzzyFilePath.sublime-package", line 4, in get_position
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\sublime.py", line 538, in __getitem__
    raise IndexError()
IndexError
Traceback (most recent call last):
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\sublime_plugin.py", line 320, in on_selection_modified_async
    callback.on_selection_modified_async(v)
  File "autofilename in D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Installed Packages\AutoFileName.sublime-package", line 171, in on_selection_modified_async
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\sublime.py", line 538, in __getitem__
    raise IndexError()
IndexError
Traceback (most recent call last):
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\sublime_plugin.py", line 320, in on_selection_modified_async
    callback.on_selection_modified_async(v)
  File "autofilename in D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Installed Packages\AutoFileName.sublime-package", line 171, in on_selection_modified_async
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\sublime.py", line 538, in __getitem__
    raise IndexError()
IndexError
```

https://github.com/BoundInCode/AutoFileName/issues/97

**Comment by sagold** [comment]
Which command do you have mapped to this right (or left) click? I cannot find any matching command in the default Sublime, AutoFileName or FuzzyFilePath commands.

**Comment by evandrocoan** [comment]
It is the right click, when used the left, nothing happens. This is my `.sublime-mousemap` for this two bottons:
```json
	{
		"button": "button1", "modifiers": ["shift", "alt"],
		"press_command": "drag_select",
		"press_args": {"subtractive": true, "extend": true}
	},
	{
		"button": "button2", "modifiers": ["shift", "alt"],
		"press_command": "drag_select",
		"press_args": {"by": "columns", "subtractive": true}
	},
```

**Comment by evandrocoan** [comment]
I was wrong, actually, it happens with both buttons, but for each one there is a different error.

For the `alt+shif+right` the error is this:
```
Traceback (most recent call last):
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\sublime_plugin.py", line 421, in on_post_text_command
    callback.on_post_text_command(v, name, args)
  File "QueryCompletionListener in D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Installed Packages\FuzzyFilePath.sublime-package", line 78, in on_post_text_command
  File "common.selection in D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Installed Packages\FuzzyFilePath.sublime-package", line 7, in get_line
  File "common.selection in D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Installed Packages\FuzzyFilePath.sublime-package", line 4, in get_position
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\sublime.py", line 538, in __getitem__
    raise IndexError()
IndexError
Traceback (most recent call last):
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\sublime_plugin.py", line 320, in on_selection_modified_async
    callback.on_selection_modified_async(v)
  File "autofilename in D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Installed Packages\AutoFileName.sublime-package", line 171, in on_selection_modified_async
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\sublime.py", line 538, in __getitem__
    raise IndexError()
IndexError
Traceback (most recent call last):
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\sublime_plugin.py", line 320, in on_selection_modified_async
    callback.on_selection_modified_async(v)
  File "autofilename in D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Installed Packages\AutoFileName.sublime-package", line 171, in on_selection_modified_async
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\sublime.py", line 538, in __getitem__
    raise IndexError()
IndexError
```

For the `alt+shif+left` the error is this:
```
Traceback (most recent call last):
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\sublime_plugin.py", line 421, in on_post_text_command
    callback.on_post_text_command(v, name, args)
  File "QueryCompletionListener in D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Installed Packages\FuzzyFilePath.sublime-package", line 78, in on_post_text_command
  File "common.selection in D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Installed Packages\FuzzyFilePath.sublime-package", line 7, in get_line
  File "common.selection in D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Installed Packages\FuzzyFilePath.sublime-package", line 4, in get_position
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\sublime.py", line 538, in __getitem__
    raise IndexError()
IndexError
Traceback (most recent call last):
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\sublime_plugin.py", line 320, in on_selection_modified_async
    callback.on_selection_modified_async(v)
  File "autofilename in D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Installed Packages\AutoFileName.sublime-package", line 171, in on_selection_modified_async
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\sublime.py", line 538, in __getitem__
    raise IndexError()
IndexError
```
