### ISSUE TITLE
Extension Stopped working

### ISSUE THREAD

**Issue by joadr** [sagold/FuzzyFilePath#34]
I guess after the update the extension stopped working

When executing extension's commands with (ctrl + shift + p) I get this:

```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 393, in on_text_command
    res = callback.on_text_command(v, name, args)
  File "QueryCompletionListener in /home/joaco/.config/sublime-text-3/Installed Packages/FuzzyFilePath.sublime-package", line 74, in on_text_command
AttributeError: 'module' object has no attribute 'get'
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 421, in on_post_text_command
    callback.on_post_text_command(v, name, args)
  File "QueryCompletionListener in /home/joaco/.config/sublime-text-3/Installed Packages/FuzzyFilePath.sublime-package", line 83, in on_post_text_command
AttributeError: 'module' object has no attribute 'get'
```

**Comment by joadr** [comment]
I get this also when I click in the console, and then on the code I get this:

Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 393, in on_text_command
    res = callback.on_text_command(v, name, args)
  File "QueryCompletionListener in /home/joaco/.config/sublime-text-3/Installed Packages/FuzzyFilePath.sublime-package", line 74, in on_text_command
AttributeError: 'module' object has no attribute 'get'
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 421, in on_post_text_command
    callback.on_post_text_command(v, name, args)
  File "QueryCompletionListener in /home/joaco/.config/sublime-text-3/Installed Packages/FuzzyFilePath.sublime-package", line 83, in on_post_text_command
AttributeError: 'module' object has no attribute 'get'

**Comment by sagold** [comment]
Hi joadr.

Yes, the update may have caused this issue. My first guess is that the update did not download completely or has not loaded correctly. Could you try to restart Sublime and if errors still occur delete and reinstall the plugin?

If you still get this error i will check why the settings module is not loaded correctly.
Thank you for your help.

**Comment by joadr** [comment]
I think restarting sublime-text worked
