### ISSUE TITLE
Line 641, in __getitem__ raise IndexError()

### ISSUE THREAD

**Issue by evandrocoan** [sagold/FuzzyFilePath#41]
It just popped on my console, but I do not know how reproduce it yet.
```
Traceback (most recent call last):
  File "D:\SublimeText\sublime_plugin.py", line 664, in on_post_text_command
    callback.on_post_text_command(v, name, args)
  File "QueryCompletionListener in D:\SublimeText\Data\Installed Packages\FuzzyFilePath.sublime-package", line 82, in on_post_text_command
  File "common.selection in D:\SublimeText\Data\Installed Packages\FuzzyFilePath.sublime-package", line 7, in get_line
  File "common.selection in D:\SublimeText\Data\Installed Packages\FuzzyFilePath.sublime-package", line 4, in get_position
  File "D:\SublimeText\sublime.py", line 641, in __getitem__
    raise IndexError()
IndexError
```

**Comment by evandrocoan** [comment]
I just find out how to reproduce this. You just need to delete all cursors/carets selections and this error is triggered immediately.

**Comment by sagold** [comment]
I close this issue when the fix is on master.

Regards,
sagold
